View Chirps

'''Chirps are separated into public and private chirps. Only the two users involved in a private chirp can see it in their Private Chirps section.'''

<< Private Chirps >>
1. BiffBoffin: Hey, you up for ping...
2. Lara_keet: Any idea what Jeff wa...
3. BiffBoffin: Hah, you got wrecked...
<< Public Chirps >>
4. Tweedleedee: Anybody know a good...
5. Fuzzy: Do NOT try the mega ultra...
6. Velton32: You guys have got to s...
...
9. Main Menu
>